# Generated by Django 5.0.2 on 2025-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('admin', 'Admin')], default='donor', max_length=10),
        ),
    ]
