# Generated by Django 5.1.6 on 2025-02-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
