# Generated by Django 5.1.6 on 2025-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_donation_description_donation_donation_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='quantity',
            new_name='item_quantity',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('monetary', 'Monetary'), ('in_kind', 'In-Kind')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_name',
            field=models.CharField(blank=True, default='Money', max_length=255, null=True),
        ),
    ]
