# Generated by Django 5.1.6 on 2025-02-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_quantity_donation_item_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='description',
            new_name='item_description',
        ),
    ]
