# Generated by Django 5.1.6 on 2025-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_description_donation_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('monetary', 'Monetary'), ('in_kind', 'In-Kind'), ('agent', 'Agent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('agent', 'Agent'), ('recipient', 'Recipient')], default='donor', max_length=10),
        ),
    ]
