# Generated by Django 5.1.6 on 2025-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
