# Generated by Django 5.1.6 on 2025-03-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_job_updated_at_alter_donation_donation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
