# Generated by Django 5.1.6 on 2025-03-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('agent', 'Agent')], default='donor', max_length=10),
        ),
    ]
