# Generated by Django 5.1.6 on 2025-03-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_donation_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='website.donation'),
        ),
    ]
