# Generated by Django 5.1.6 on 2025-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_donation_status_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='city',
        ),
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
