# Generated by Django 5.1.6 on 2025-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_donation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='location',
        ),
        migrations.AddField(
            model_name='agent',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
