# Generated by Django 5.1.6 on 2025-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_agent_location_agent_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
