# Generated by Django 5.1.7 on 2025-04-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['-priority_score'], 'verbose_name': 'Donation Recipient', 'verbose_name_plural': 'Donation Recipients'},
        ),
        migrations.AddField(
            model_name='recipient',
            name='last_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='priority_score',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='urgency_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='population',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
