# Generated by Django 5.1.7 on 2025-04-01 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_recipient_options_recipient_last_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('medical', 'Medical'), ('education', 'Education'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('other', 'Other')], help_text='Broad category of need', max_length=20)),
                ('name', models.CharField(help_text='Specific name of needed item/service', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the need', null=True)),
                ('quantity_needed', models.PositiveIntegerField(default=1, help_text='Total quantity required')),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='Quantity already received')),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('items', 'Items'), ('boxes', 'Boxes'), ('hours', 'Hours')], default='items', help_text='Unit of measurement', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=3, help_text='How urgently this is needed')),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_fulfilled', models.BooleanField(default=False, help_text='Mark if this need has been completely fulfilled')),
            ],
            options={
                'verbose_name_plural': 'Needs',
                'ordering': ['-priority', 'date_logged'],
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='donation',
            name='assigned_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to='website.recipient', verbose_name='Assigned Recipient'),
        ),
        migrations.AddField(
            model_name='donation',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='donation',
            name='fulfillment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='fulfillment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='fulfillment_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Percentage of donation actually fulfilled'),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='preferred_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('partially_fulfilled', 'Partially Fulfilled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='website_don_status_8f2d02_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_type'], name='website_don_donatio_b6daf9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['assigned_recipient'], name='website_don_assigne_92b47c_idx'),
        ),
        migrations.AddField(
            model_name='need',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='website.recipient'),
        ),
    ]
