# Generated by Django 5.1.7 on 2025-04-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_need_alter_donation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
        migrations.AlterField(
            model_name='donation',
            name='assigned_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to='website.recipient'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='fulfillment_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
