# Generated by Django 5.1.7 on 2025-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
