# Generated by Django 5.1.7 on 2025-04-08 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_agent_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='id_number',
            field=models.PositiveIntegerField(default=100000, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
