# Generated by Django 5.1.7 on 2025-04-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_agent_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled for Pickup'), ('in_progress', 'In Progress (Picked Up)'), ('in_transit', 'In Transit'), ('partially_fulfilled', 'Partially Fulfilled'), ('completed', 'Completed (Delivered)'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
