# Generated by Django 5.1.7 on 2025-04-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_donation_delivered_quantity_alter_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='fulfillment_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='need',
            name='partially_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled for Pickup'), ('in_progress', 'In Progress (Picked Up)'), ('in_transit', 'In Transit'), ('completed', 'Completed (Delivered)'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='need',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('medical', 'Medical'), ('education', 'Education'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='need',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='need',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='need',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=3),
        ),
        migrations.AlterField(
            model_name='need',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='need',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='need',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('items', 'Items'), ('boxes', 'Boxes'), ('hours', 'Hours')], default='items', max_length=10),
        ),
    ]
