# Generated by Django 5.1.7 on 2025-04-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_need_fulfillment_history_need_partially_fulfilled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='delivered_quantity',
        ),
        migrations.RemoveField(
            model_name='need',
            name='fulfillment_history',
        ),
        migrations.RemoveField(
            model_name='need',
            name='partially_fulfilled',
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('partially_fulfilled', 'Partially Fulfilled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='need',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('medical', 'Medical'), ('education', 'Education'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('other', 'Other')], help_text='Broad category of need', max_length=20),
        ),
        migrations.AlterField(
            model_name='need',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the need', null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='is_fulfilled',
            field=models.BooleanField(default=False, help_text='Mark if this need has been completely fulfilled'),
        ),
        migrations.AlterField(
            model_name='need',
            name='name',
            field=models.CharField(help_text='Specific name of needed item/service', max_length=255),
        ),
        migrations.AlterField(
            model_name='need',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=3, help_text='How urgently this is needed'),
        ),
        migrations.AlterField(
            model_name='need',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity required'),
        ),
        migrations.AlterField(
            model_name='need',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0, help_text='Quantity already received'),
        ),
        migrations.AlterField(
            model_name='need',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('items', 'Items'), ('boxes', 'Boxes'), ('hours', 'Hours')], default='items', help_text='Unit of measurement', max_length=10),
        ),
        migrations.CreateModel(
            name='DonationCompletionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='donation_completion_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_photos', to='website.donation')),
            ],
        ),
    ]
