# Generated by Django 5.2.3 on 2025-06-19 09:54

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_donation_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcompletionphoto',
            name='photo',
            field=models.ImageField(upload_to=website.models.DonationCompletionPhoto.upload_to_path),
        ),
    ]
